######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 6 08:34:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
